{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-proxy.fullname" . }}
  labels:
    {{- include "auth-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.gotrueUrl }}
  GOTRUE_URL: {{ .Values.secrets.gotrueUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.gotrueAnonKey }}
  GOTRUE_ANON_KEY: {{ .Values.secrets.gotrueAnonKey | quote }}
  {{- end }}
  {{- if .Values.secrets.attestationIosBundleId }}
  ATTESTATION_IOS_BUNDLE_ID: {{ .Values.secrets.attestationIosBundleId | quote }}
  {{- end }}
  {{- if .Values.secrets.attestationIosTeamId }}
  ATTESTATION_IOS_TEAM_ID: {{ .Values.secrets.attestationIosTeamId | quote }}
  {{- end }}
  {{- if .Values.secrets.attestationAndroidPackage }}
  ATTESTATION_ANDROID_PACKAGE: {{ .Values.secrets.attestationAndroidPackage | quote }}
  {{- end }}
  {{- if .Values.secrets.attestationGcpProjectId }}
  ATTESTATION_GCP_PROJECT_ID: {{ .Values.secrets.attestationGcpProjectId | quote }}
  {{- end }}
  {{- if .Values.secrets.attestationGcpCredentialsFile }}
  ATTESTATION_GCP_CREDENTIALS_FILE: {{ .Values.secrets.attestationGcpCredentialsFile | quote }}
  {{- end }}
  {{- if .Values.secrets.redisAddr }}
  REDIS_ADDR: {{ .Values.secrets.redisAddr | quote }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
{{- end }}
